language: python

python:
  - "3.5"
  - "3.6"

env:
  - MYSQL_PACKAGE=pymysql
  - MYSQL_PACKAGE=mysqlclient

services:
  - postgresql
  - mysql

install:
  - pip install -r tests-requirements.txt -U
  - if [[ $MYSQL_PACKAGE == 'pymysql' ]]; then pip install pymysql; fi
  - if [[ $MYSQL_PACKAGE == 'mysqlclient' ]]; then pip install mysqlclient; fi

script: pytest tests

before_script:
  - psql -c 'create database orator_test;' -U postgres
  - mysql -u root -e 'create database orator_test;'
